### ISSUE TITLE
on change event not triggering

### ISSUE THREAD

**Issue by arigoldx** [hacklanta/lift-formality#29]
We're trying

```
    val connectionConfiguration =
      field[String]("#connection-configuration-value") ?
        notEmpty ->
        on("change", { id: String =>
          println(s"\n\n------------------ on change triggered, id:[$id] -------------------\n\n")
          JsCmds.Alert(s"NEW ID: $id")
        })
```

but see neither the Alert nor the println.

Inspecting the element shows something bound to the on change event,

```
<input onchange="lift.ajax('F1370353388993HAMDAL=' + encodeURIComponent(this.value), null, null, null)" name="F1370353388992ZFYZE2" type="hidden" id="connection-configuration-value" value="9be95cfe_f62c_4e99_a7b7_43bb3fe12153">
```

and while value does indeed change, nothing happens.

I'm preeeetty sure I copied the [example code](https://github.com/hacklanta/lift-formality#event-handling) correctly... any ideas?

**Comment by Shadowfiend** [comment]
Interesting… Are you getting any issues with Content Security Policy perhaps?

**Comment by arigoldx** [comment]
Holy moley I think we are!

Thanks -- I'll give that some :eyes:.

**Comment by Shadowfiend** [comment]
My guess is that you may have `inline` content disallowed, but lift-formality currently attaches event handlers as inline JS <_<

**Comment by arigoldx** [comment]
Well whaddaya know, we might be ok here. Nearly positive that the issue was that the `onchange` event wasn't getting triggered at all.

Here's my reasoning. We use the publicly available [elemica-suggest](https://github.com/elemica/elemica-suggest) library and of course were binding the form to the `valueInput`. I was under the impression that changing the value would trigger `onchange` but [nope](https://stackoverflow.com/questions/3179385/val-doesnt-trigger-change-in-jquery). The workaround shouldn't be all that hard.

Regarding the CSP issue: I'm under the impression that we're ok (and lift-formality is ok) because the inline JS is from the same site as the page. But maybe I missing something and we just got lucky? We had been seeing CSP issues with google fonts but somehow, um, they fixed themselves -- I can't reproduce them and don't see them anymore.

Pardon the interruption & thanks for the rubberduckin'!

**Comment by arigoldx** [comment]
I'm feelin' remiss not describing the workaround: we're going to use elemica-suggest's `afterSelect` function to trigger the `change` event for the `valueInput`. In fact, now that I'm looking around, we've done this exact thing before 😅

**Comment by Shadowfiend** [comment]
@arigoldx reallll late followup, but it feels like we can close this issue?

**Comment by arigoldx** [comment]
Indeed :)
